[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
upload_port = COM6
monitor_port = COM6
monitor_speed = 115200
board_build.filesystem = littlefs

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = COM6
monitor_port = COM6
monitor_speed = 115200
board_build.filesystem = littlefs
